spring.application.name=paysphere
spring.datasource.url=jdbc:mysql://172.31.7.42:3306/paysphere
spring.datasource.username=paysphere
spring.datasource.password=PaySphere@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8090